version: "3.3"

services:
  skuska:
    restart: always
    image: sameersbn/postgresql:10-2
    environment:
      - PG_TRUST_LOCALNET=true
      - DB_NAME=skuska
      - DB_USER=postgres
      - DB_PASS=postgres
      - PG_RUNDIR=/run/postgres
      - PD_LOGDIR=/var/log/postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql
      - logs:/var/log/postgresql

  backend:
    image: be
    ports:
      - "8080:8080"

  frontend:
    image: fe
    ports:
      - "80:80"

volumes:
  data:
  logs:
